baseURL = 'https://f49560a2.personal-blog-4pt.pages.dev/'
languageCode = 'en-us'
title = 'Personal Blog'

theme = 'mainroad'

# URL configuration
canonifyURLs = true
relativeURLs = false

# Pagination
[pagination]
pagerSize = 10